[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
enet-cs-sys = "0.1.1"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
protobuf = "3.3.0"
rust-common = { path = "../rust-common" }
