[package]
name = "rust-client-game"
version = "0.1.0"
edition = "2021"


[dependencies]
avian2d = "0.2.0"
bevy = { version = "0.15.0", default-features = true, features = ["multi_threaded", "bevy_state", "serialize"] }
bevy_ecs_tilemap = { version = "0.15"}
bevy_simple_text_input = "0.10"
bevy_transform_interpolation = "0.1"
leafwing-input-manager = "0.16"
lightyear = { version = "0.18", features = ["avian2d", "leafwing"] }
rand = "0.8"
rust-common-game = { path = "../rust-common-game" }
serde = { version = "1.0.215", features = ["derive"] }

 