[package]
name = "rust-client-game"
version = "0.1.0"
edition = "2021"


[dependencies]
avian2d = "0.1.2"
bevy = { version = "0.14", default-features = true, features = ["multi_threaded", "bevy_state", "serialize"] }
bevy_simple_text_input = "0.9"
bevy_transform_interpolation = { git = "https://github.com/Jondolf/bevy_transform_interpolation", rev = "93b7036" }
leafwing-input-manager = "0.15"
lightyear = { version = "0.17", features = ["avian2d", "leafwing"] }
rand = "0.8"
rust-common-game = { path = "../rust-common-game" }
serde = { version = "1.0.215", features = ["derive"] }

 