[workspace]
members = [
    "rust-client-v2",
    "rust-common",
    "rust-lambda-auth",
    "rust-lambda-common",
    "rust-lambda-lobby",
    "rust-lambda-scaler",
    "rust-server-common",
    "rust-server-game",
    "rust-server-test",
]
resolver = "2"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3