[workspace]
members = [
    "rust-client",
    "rust-common",
    "rust-lambda-auth",
    "rust-lambda-common",
    "rust-lambda-lobby",
    "rust-lambda-scaler",
    "rust-server-common",
    "rust-server-game",
    "rust-server-test",
]
resolver = "2"