[package]
name = "rust-common"
version = "0.1.0"
edition = "2021"


[dependencies]
bytes = "1.8.0"
glam = { version = "0.29.2" }
prost = "0.12.6"
reqwest = { version = "0.12.9" }
tokio = { version = "1.41.1" }

[build-dependencies]
dotenvy = "0.15.7"
prost-build = "0.5"