[package]
name = "rust-common"
version = "0.1.0"
edition = "2021"


[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [ "experimental-threads" ] }
protobuf = "3.3.0"

[build-dependencies]
protobuf-codegen = "3.3.0"
protoc-bin-vendored = "3.0.0"