version: '3.9'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      TARGET_ENV: local
      SERVER_GAME_IP: 0.0.0.0